Repository googleapis/java-dialogflow, pull requests merged in 2020-11, with the labels that each got.

#348 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#352 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#355 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#357 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#359 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#365 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#358 docs: Update doc on ReloadDocument method.
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsGrpc.java
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/document.proto
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#370 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#371 chore: remove clirr ignored differences
  google-cloud-dialogflow/clirr-ignored-differences.xml
  grpc-google-cloud-dialogflow-v2/clirr-ignored-differences.xml
  grpc-google-cloud-dialogflow-v2beta1/clirr-ignored-differences.xml
Labels: api: dialogflow, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#378 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#380 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#382 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full, samples
