Repository googleapis/java-dialogflow, pull requests merged in 2020-09, with the labels that each got.

#278 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#277 docs: wording updates for tiers
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/OriginalDetectIntentRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/OriginalDetectIntentRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/webhook.proto
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#280 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#286 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#299 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#300 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: dialogflow, automerge, cla: yes

#305 docs: update OPTIONAL annotations for some fields.
  README.md
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#308 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
