Repository googleapis/java-dialogflow, pull requests merged in 2020-12, with the labels that each got.

#389 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#391 chore: added retry for flaky test
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/com/example/dialogflow/CreateDocumentTest.java
Labels: api: dialogflow, cla: yes

#395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#405 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#407 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full
