Repository googleapis/java-dialogflow, pull requests merged in 2021-05, with the labels that each got.

#539 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#541 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: dialogflow, automerge, cla: yes

#546 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#551 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#553 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#558 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#559 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#561 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#563 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#565 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#493 samples: updated legacy field
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentStream.java
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentWithLocation.java
  samples/snippets/src/test/java/com/example/dialogflow/CreateDocumentTest.java
  samples/snippets/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAndTextToSpeechIT.java
Labels: api: dialogflow, cla: yes, samples

#568 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#569 samples: updated legacy field in detect intent knowledge
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
Labels: api: dialogflow, cla: yes, samples

#557 feat: added location-aware HTTP path binding for ListIntents
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/IntentsClient.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentProto.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ListIntentsRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ListIntentsRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/intent.proto
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#570 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#571 samples: updated legacy field in detect intent audio
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentAudio.java
Labels: api: dialogflow, cla: yes, samples

#572 samples: updated legacy field in detect intent texts
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentTexts.java
Labels: api: dialogflow, cla: yes, samples

#575 samples: updated legacy field in detect intent samples
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentWithLocation.java
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
  samples/snippets/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
Labels: api: dialogflow, cla: yes, samples

#574 feat: added location-aware HTTP path binding for ListIntents
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentsClient.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResult.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/QueryResultOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionProto.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/session.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AutomatedAgentReply.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AutomatedAgentReplyOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentProto.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ListIntentsRequest.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ListIntentsRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ParticipantProto.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResult.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/QueryResultOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionProto.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/StreamingRecognitionResult.java
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/environment.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/intent.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/participant.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/session.proto
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full
