Repository googleapis/java-dialogflow, pull requests merged in 2021-03, with the labels that each got.

#457 feat(generator): update protoc to v3.15.3
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/BatchUpdateEntityTypesRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/BatchUpdateEntityTypesRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/BatchUpdateIntentsRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/BatchUpdateIntentsRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ExportAgentResponse.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ExportAgentResponseOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ImportAgentRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ImportAgentRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/RestoreAgentRequest.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/RestoreAgentRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/BatchUpdateEntityTypesRequest.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/BatchUpdateEntityTypesRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/BatchUpdateIntentsRequest.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/BatchUpdateIntentsRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Document.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ExportAgentResponse.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ExportAgentResponseOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ImportAgentRequest.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ImportAgentRequestOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/Intent.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/RestoreAgentRequest.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/RestoreAgentRequestOrBuilder.java
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#459 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#467 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#465 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#474 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#469 feat(v2beta1): remote MixedAudio from ResponseMessage
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AgentsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/AnswerRecordsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ContextsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ConversationProfilesGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ConversationsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/DocumentsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/EntityTypesGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/EnvironmentsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/KnowledgeBasesGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ParticipantsGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypesGrpc.java
  grpc-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/SessionsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AnswerRecordsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ContextsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationProfilesGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypesGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EnvironmentsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ParticipantsGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypesGrpc.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionsGrpc.java
  proto-google-cloud-dialogflow-v2beta1/clirr-ignored-differences.xml
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ParticipantProto.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ResponseMessage.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ResponseMessageOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/participant.proto
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#482 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dialogflow, automerge, cla: yes

#489 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: dialogflow, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#483 fix!: remove resource_reference for invisible resources
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/AgentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/AnswerRecordsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/ContextsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/ConversationProfilesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/ConversationsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/DocumentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/EntityTypesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/EnvironmentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/IntentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/KnowledgeBasesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/ParticipantsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/SessionEntityTypesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/AnswerRecordsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/ContextsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationProfilesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/DocumentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/EntityTypesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/EnvironmentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/IntentsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/KnowledgeBasesClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/ParticipantsClient.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/SessionEntityTypesClient.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockAgentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockAnswerRecordsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockContextsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockConversationProfilesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockConversationsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockDocumentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockEntityTypesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockEnvironmentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockIntentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockKnowledgeBasesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockParticipantsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockSessionEntityTypesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/MockSessionsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockAgentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockAnswerRecordsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockContextsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockConversationProfilesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockConversationsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockDocumentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockEntityTypesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockEnvironmentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockIntentsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockKnowledgeBasesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockParticipantsImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockSessionEntityTypesImpl.java
  google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2beta1/MockSessionsImpl.java
  grpc-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ParticipantsGrpc.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ConversationProfileProto.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/HumanAgentAssistantConfig.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/conversation_profile.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationProfileProto.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/HumanAgentAssistantConfig.java
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/conversation_profile.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/participant.proto
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#492 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dialogflow, cla: yes, context: full

#494 chore: clean up clirr ignored differences
  proto-google-cloud-dialogflow-v2/clirr-ignored-differences.xml
  proto-google-cloud-dialogflow-v2beta1/clirr-ignored-differences.xml
Labels: api: dialogflow, automerge, cla: yes
