Repository googleapis/java-dialogflow, pull requests merged in 2021-08, with the labels that each got.

#635 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: dialogflow, automerge, cla: yes

#629 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: dialogflow, automerge, context: full

#641 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: dialogflow, automerge

#633 docs: fix typos
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ValidationError.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ValidationErrorOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/validation_result.proto
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ValidationError.java
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ValidationErrorOrBuilder.java
  proto-google-cloud-dialogflow-v2beta1/src/main/proto/google/cloud/dialogflow/v2beta1/validation_result.proto
  synth.metadata
Labels: cla: yes, api: dialogflow, context: full

#636 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: cla: yes, api: dialogflow, automerge

#622 feat: deprecate ofProjectLocationAgentName and ofProjectAgentName
  proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/AgentName.java
  synth.metadata
  synth.py
Labels: cla: yes, api: dialogflow, automerge

#648 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge

#650 feat: expose `Locations` service to get/list avaliable locations of Dialogflow products; fixed some API annotations
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/Intent.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentOrBuilder.java
  proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/IntentProto.java
  proto-google-cloud-dialogflow-v2/src/main/proto/google/cloud/dialogflow/v2/intent.proto
  synth.metadata
Labels: cla: yes, api: dialogflow, automerge, context: full

#657 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge

#652 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: dialogflow, automerge, context: full

#663 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: dialogflow, automerge

#666 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge

#679 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge

#658 chore: update gapic-generator-java version to 2.1.0
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AgentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/AnswerRecordsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/ContextsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/ConversationProfilesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/ConversationsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/DocumentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/EntityTypesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/EnvironmentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/FulfillmentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/IntentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/KnowledgeBasesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/ParticipantsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/SessionEntityTypesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/SessionsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/stub/VersionsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AgentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/AnswerRecordsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/ContextsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/ConversationProfilesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/ConversationsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/DocumentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/EntityTypesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/EnvironmentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/FulfillmentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/IntentsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/KnowledgeBasesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/ParticipantsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/SessionEntityTypesStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/SessionsStubSettings.java
  google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2beta1/stub/VersionsStubSettings.java
  synth.metadata
Labels: cla: yes, api: dialogflow, automerge, context: full

#672 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: dialogflow, automerge, context: full

#683 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge

#639 samples: add update intent code sample
  samples/snippets/src/main/java/com/example/dialogflow/UpdateIntent.java
  samples/snippets/src/test/java/com/example/dialogflow/UpdateIntentIT.java
Labels: cla: yes, api: dialogflow, samples

#684 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: dialogflow, automerge
